VLIB := vlib
VMAP := vmap
VCOM := vcom
VLOG := vlog
VSIM := vsim

VLIB_FLAGS :=
VMAP_FLAGS :=
VCOM_FLAGS :=
VLOG_FLAGS :=
VSIM_FLAGS := {{vsim_flags}}

include project.mk
-include cocotb.mk

.PHONY: clean compile simulate gui

ifeq ($(DO_CMD),)
DO_CMD := -do "run -all; quit"
else
GUI_DO_CMD := $(DO_CMD)
endif

simulate: compile
	$(VSIM) $(VSIM_FLAGS) $(TOPLEVELS) -c $(DO_CMD)


gui: compile
	$(VSIM) $(VSIM_FLAGS) $(TOPLEVELS) $(GUI_DO_CMD)


compile: $(VERILOG_FILESETS) $(VHDL_FILESETS) | $(LIBRARIES)


$(LIBRARIES):
	$(VLIB) $@
	$(VMAP) $@ $@


include *.files


%-vhdl.fileset.com: %-vhdl.fileset %-vhdl.files
	$(VCOM) $(VCOM_FLAGS) -f $<
	@touch $@


%-verilog.fileset.com: %.verilog.fileset %-verilog.files
	$(VLOG) $(VLOG_FLAGS) -f $<
	@touch $@


%-systemverilog.fileset.com: %-systemverilog.fileset %-systemverilog.files
	$(VLOG) $(VLOG_FLAGS) -f $<
	@touch $@


clean:
	rm -rf $(LIBRARIES) transcript *.wlf *.vcd *.com modelsim.ini
